// GENERATED by scripts/build-migrations.mjs — do not edit by hand.
// Regenerate with `npm run db:generate` after any schema change.

const journal = {
  "version": "7",
  "dialect": "sqlite",
  "entries": [
    {
      "idx": 0,
      "version": "6",
      "when": 1788981313530,
      "tag": "0000_quick_the_call",
      "breakpoints": true
    }
  ]
};

const migrations: Record<string, string> = {
  m0000: `CREATE TABLE \`nails\` (
	\`id\` text PRIMARY KEY NOT NULL,
	\`photo_id\` text NOT NULL,
	\`finger_id\` text NOT NULL,
	\`crop_uri\` text NOT NULL,
	FOREIGN KEY (\`photo_id\`) REFERENCES \`photos\`(\`id\`) ON UPDATE no action ON DELETE cascade
);
--> statement-breakpoint
CREATE INDEX \`nails_photo_id_idx\` ON \`nails\` (\`photo_id\`);--> statement-breakpoint
CREATE INDEX \`nails_finger_id_idx\` ON \`nails\` (\`finger_id\`);--> statement-breakpoint
CREATE UNIQUE INDEX \`nails_photo_finger_unq\` ON \`nails\` (\`photo_id\`,\`finger_id\`);--> statement-breakpoint
CREATE TABLE \`photos\` (
	\`id\` text PRIMARY KEY NOT NULL,
	\`captured_at\` integer NOT NULL,
	\`file_uri\` text NOT NULL,
	\`thumb_uri\` text NOT NULL,
	\`hand\` text NOT NULL,
	\`width\` integer NOT NULL,
	\`height\` integer NOT NULL,
	\`normalised_orientation\` integer NOT NULL,
	\`reference_photo_id\` text,
	FOREIGN KEY (\`reference_photo_id\`) REFERENCES \`photos\`(\`id\`) ON UPDATE no action ON DELETE set null
);
--> statement-breakpoint
CREATE INDEX \`photos_captured_at_idx\` ON \`photos\` (\`captured_at\`);--> statement-breakpoint
CREATE INDEX \`photos_hand_idx\` ON \`photos\` (\`hand\`);--> statement-breakpoint
CREATE INDEX \`photos_reference_photo_id_idx\` ON \`photos\` (\`reference_photo_id\`);--> statement-breakpoint
CREATE TABLE \`relapses\` (
	\`id\` text PRIMARY KEY NOT NULL,
	\`occurred_at\` integer NOT NULL,
	\`note\` text,
	\`ended_streak_id\` text,
	FOREIGN KEY (\`ended_streak_id\`) REFERENCES \`streaks\`(\`id\`) ON UPDATE no action ON DELETE set null
);
--> statement-breakpoint
CREATE INDEX \`relapses_occurred_at_idx\` ON \`relapses\` (\`occurred_at\`);--> statement-breakpoint
CREATE TABLE \`settings\` (
	\`key\` text PRIMARY KEY NOT NULL,
	\`value\` text NOT NULL
);
--> statement-breakpoint
CREATE TABLE \`streaks\` (
	\`id\` text PRIMARY KEY NOT NULL,
	\`started_at\` integer NOT NULL,
	\`ended_at\` integer
);
--> statement-breakpoint
CREATE INDEX \`streaks_started_at_idx\` ON \`streaks\` (\`started_at\`);--> statement-breakpoint
CREATE UNIQUE INDEX \`streaks_single_active_unq\` ON \`streaks\` ((1)) WHERE "streaks"."ended_at" is null;--> statement-breakpoint
CREATE TABLE \`triggers\` (
	\`id\` text PRIMARY KEY NOT NULL,
	\`occurred_at\` integer NOT NULL,
	\`activity\` text,
	\`mood\` text
);
--> statement-breakpoint
CREATE INDEX \`triggers_occurred_at_idx\` ON \`triggers\` (\`occurred_at\`);`,
};

/** Consumed by `useMigrations` / `migrate` from `drizzle-orm/expo-sqlite/migrator`. */
export default { journal, migrations };
